### PR TITLE
DowngradeStaticTypeDeclarationRector: removed dead code

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by samsonasik** [comment]
No, the different variable is on purpose so it assigned in the loop to be checked.

**Comment by staabm** [comment]
the variable gets immediately overwritten in the loop (and its not used after the loop)

**Comment by samsonasik** [comment]
That is used to fill `hasChanged` once it true, the node need to be returned to avoid it changed on next param.

**Comment by staabm** [comment]
phpstorm agrees that this variable is dead code

grafik

**Comment by samsonasik** [comment]
Oh, I see, that always replaced, let's reopen and merge 👍

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @staabm

**Pull request merged**
