### PR TITLE
[CI] Enable zend.assertions ini values in CI

### PR DESCRIPTION
**Pull request by samsonasik**
To show error per fixture https://github.com/rectorphp/rector-downgrade-php/pull/55#discussion_r1193003900

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the `isFirstClassCallable()` seems already called on `shouldSkip()` method, so it works

https://github.com/rectorphp/rector-downgrade-php/blob/86a937c9c1b31ed702070cb39f2ee2d4748f545b/rules/DowngradePhp70/Rector/Expression/DowngradeDefineArrayConstantRector.php#L86-L88

however, the `zend.assertions` is needed to be set to 1 to show error early.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready, as per target rule already use `$funcCall->isFirstClassCallable()`, it doesn't show error.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
