### PR TITLE
DowngradeArrayFilterNullableCallbackRector: Cheap checks first

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by samsonasik** [comment]
I think this not matter, since nodeNameResolver target service is cached so it will always resolve single service that match to target node

**Comment by staabm** [comment]
`isName` calls at least another 5 functions. we pay this cost for every FuncCall in the codebase beeing downgraded

**Comment by samsonasik** [comment]
while correct, I prefer more easy to follow code structure: check the name, check the arg, process, instead of check of arg, check name, process.

**Comment by TomasVotruba** [comment]
I agree with @samsonasik , if this is not making run more than 10 % faster, code readability is preffered.

**Pull request closed without merging**
