### PR TITLE
Rename fixture to fix test after disable nodeConnectingVisitorCompatibility

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba this PR needs to be merged first to accomodate updated cache PHPStan after `nodeConnectingVisitorCompatibility: false` explicitly set on PR:

- https://github.com/rectorphp/rector-src/pull/4841

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba let's merge it ;)

**Comment by staabm** [comment]
I wonder why this tests were depending on `nodeConnectingVisitorCompatibility` ?

**Comment by samsonasik** [comment]
it's not, it about PHPStan cache, if PHPStan config updated, the PHPStan seems rebuild and on some area, the fixture need rename to avoid conflict with other fixture with same name.

**Comment by staabm** [comment]
hmm does it mean we should have a phpstan rule which makes sure class names in test-cases are unique?

**Pull request merged**
