### PR TITLE
[DowngradePhp80] Rollback to change match to switch on DowngradeMatchToSwitchRector

### PR DESCRIPTION
**Pull request by samsonasik**
See https://github.com/rectorphp/rector-downgrade-php/pull/112#issuecomment-1614406666
Closes https://github.com/rectorphp/rector-downgrade-php/pull/137
Fixes https://github.com/rectorphp/rector/issues/8033

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba @leoloso I rolled back fixtures to change to switch back instead of ternary. I will check:

- ensure parent node to be removed again
- ensure no left over fixture from https://github.com/rectorphp/rector-downgrade-php/pull/112 ;)

**Comment by samsonasik** [comment]
@TomasVotruba @leoloso it rolled back, next todo: removing parent attribute to have same goal of original PR: remove parent attribute ;)

**Comment by TomasVotruba** [comment]
@samsonasik  Feel free to merge fow now :+1: 

The parent removal is still needed though :)

**Comment by samsonasik** [comment]
Yes, on progress: reduce parent step 1: on ArrowFunction https://github.com/rectorphp/rector-downgrade-php/pull/139/commits/6a9944a2c6d84cf0ed1a6df8969ce0cde307c1a6

**Comment by samsonasik** [comment]
@TomasVotruba I will try remove the parent as well ;)

**Comment by samsonasik** [comment]
@TomasVotruba @leoloso it fixed now, the code complexity phpstan need to be resolved in separate PR ;),  I am merging it;)

**Pull request merged**
