### PR TITLE
[DowngradePhp84] Add DowngradeNewMethodCallWithoutParenthesesRector

### PR DESCRIPTION
**Pull request by samsonasik**
To downgrade new method call without parentheses for php 8.4 https://wiki.php.net/rfc/new_without_parentheses

Ref to allow feature https://github.com/rectorphp/rector/issues/8701, the downgrade rule need to exists on the first place.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
It seems allow constant, static property, static method, property, invoke, array array dim fetch as well based on https://wiki.php.net/rfc/new_without_parentheses

I think we can use this MethodCall as starting point, add more nodes later.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by samsonasik** [comment]
@TomasVotruba let's merge 👍

**Pull request merged**
