### PR TITLE
[DowngradePhp74] Skip same return type on DowngradeCovariantReturnTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7768

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @defunctl

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by defunctl** [comment]
@samsonasik thanks a lot for taking care of this! 

Does this cover the test scenario where the child defines the explicit sub-type of the interface, which is perfectly valid in PHP7.4+, which should transform the return type from the concrete to interface in PHP <7.4.

I only ask because I don't see the fixture for that specific scenario in the PR, but I'm not sure if it's covered elsewhere in the code base.

Before, e.g. PHP8.0:

```php
/**
 * @extends Handler<TempResponse>
 */
final class SkipSameReturnType extends Handler
{
    protected function set(): TempResponse {
        return new TempResponse();
    }
}
```

After, e.g PHP7.3/PHP7.2:

```php
/**
 * @extends Handler<TempResponse>
 */
final class SkipSameReturnType extends Handler
{
    protected function set(): ResponseInterface {
        return new TempResponse();
    }
}
```

**Comment by samsonasik** [comment]
@defunctl yes, I added sub return type fixture as well https://github.com/rectorphp/rector-downgrade-php/pull/46/commits/84c68a4524c9a5ab7825f2ed1a6e26a7ed0bbfba

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Pull request merged**
