### PR TITLE
[DowngradePhp80] Handle return throw on DowngradeThrowExprRector

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector-src/actions/runs/3593996364/jobs/6051685236#step:14:71

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1: You were faster and more elegant :)

**Comment by TomasVotruba** [comment]
While we're at it... could you handle this one too?

``php
  > 77|             if (!isset($backedEnumClassName::tryFrom($backedEnumValue))) {
```

![Screenshot from 2022-12-01 16-48-19](https://user-images.githubusercontent.com/924196/205097366-797552eb-30a3-40fd-8a7a-681744f8160f.png)

**Comment by samsonasik** [comment]
We still got another issues: `trait clone`, `coalesce inside Expr inside concat`, and `enum`: 

```bash
Parse error: rector-prefixed-downgraded/vendor/symfony/var-exporter/LazyGhostTrait.php:16
    14| use RectorPrefix202212\Symfony\Component\VarExporter\Internal\LazyObjectRegistry as Registry;
    15| use RectorPrefix202212\Symfony\Component\VarExporter\Internal\LazyObjectState;
  > 16| trait LazyGhostTrait
    17| {
    18|     /**
RectorPrefix202212\Symfony\Component\VarExporter\LazyGhostTrait::__clone() cannot declare a return type in rector-prefixed-downgraded/vendor/symfony/var-exporter/LazyGhostTrait.php on line 16
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/dependency-injection/Compiler/RegisterServiceSubscribersPass.php:79
    77|                 $key = $type->key;
    78|                 $attributes = $type->attributes;
  > 79|                 $type = ($type->nullable ? '?' : '') . ($type->type ?? throw new InvalidArgumentException(\sprintf('When "%s::getSubscribedServices()" returns "%s", a type must be set.', $class, SubscribedService::class)));
    80|             }
    81|             if (!\is_string($type) || !\preg_match('/(?(DEFINE)(?<cn>[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*+))(?(DEFINE)(?<fqcn>(?&cn)(?:\\\\(?&cn))*+))^\\??(?&fqcn)(?:(?:\\|(?&fqcn))*+|(?:&(?&fqcn))*+)$/', $type)) {
Unexpected 'throw' (T_THROW) in rector-prefixed-downgraded/vendor/symfony/dependency-injection/Compiler/RegisterServiceSubscribersPass.php on line 79
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/dependency-injection/EnvVarProcessor.php:77
    75|                 throw new RuntimeException(\sprintf('"%s" is not a "%s".', $backedEnumClassName, \BackedEnum::class));
    76|             }
  > 77|             if (!isset($backedEnumClassName::tryFrom($backedEnumValue))) {
    78|                 throw new RuntimeException(\sprintf('Enum value "%s" is not backed by "%s".', $backedEnumValue, $backedEnumClassName));
    79|             }
Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in rector-prefixed-downgraded/vendor/symfony/dependency-injection/EnvVarProcessor.php on line 77
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Output/AnsiColorMode.php:18
    16|  * @author Julien Boudry <julien@condorcet.vote>
    17|  */
  > 18| enum AnsiColorMode
    19| {
    20|     /*
Unexpected 'AnsiColorMode' (T_STRING) in rector-prefixed-downgraded/vendor/symfony/console/Output/AnsiColorMode.php on line 1
```

I don't know how to handle enum part, it is still active issue in rector/rector:

- https://github.com/rectorphp/rector/issues/7013

**Comment by TomasVotruba** [comment]
I'm checking the same output. The enum could be simple, as only used in terminal and we can create custom callback to replace with string values.

**Comment by TomasVotruba** [comment]
Also, the was exporter package could be removed possibly :thinking:

**Comment by TomasVotruba** [comment]
I'm gonna handle the `void` on clone: https://3v4l.org/Wgj19

**Comment by TomasVotruba** [comment]
Done https://github.com/rectorphp/rector-downgrade-php/commit/881256be736a828e963cb4e3a49c9d7fbc23212d :heavy_check_mark:

**Pull request merged**
